### ISSUE TITLE
Can't build dockerimage

### ISSUE THREAD

**Issue by sandert-k8s** [ValentinoUberti/mass-quay-configurator#2]
Hi, 

The current Dockerfile can't be build anymore. The minimum Rust version is 1.70. When upgrading the rust version, glibc isn't found when executing mqc. Tried with rust 1.70 and 1.75, both don't work. 
`/target/release/mqc: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /target/release/mqc)`

**Comment by sandert-k8s** [comment]
Thanks for merging the fix. Can you create a new release tag @ValentinoUberti ? Thanks!

**Comment by ValentinoUberti** [comment]
Sure!

**Comment by ValentinoUberti** [comment]
A release tag has been created! Thank you
